src/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoxController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\BoxTemplateController;
use App\Http\Controllers\TransactionController;

require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', function () {
        return redirect("/boxes/".Auth::user()->box->id);
    });

    Route::resource('permissions', PermissionController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('transactions', TransactionController::class);
    Route::resource('boxTemplates', BoxTemplateController::class);
    Route::resource('boxes', BoxController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('orders', OrderController::class);
});

src/app/Models/BoxTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BoxTemplate extends Model
{
    use HasFactory;

    public $table = "box_templates";

    protected $guarded = [];

    public function products () {
        return $this->belongsToMany(Product::class)->orderBy('box_template_product.created_at')->withPivot(['target']);
    }

    public function boxes () {
        return $this->hasMany(Box::class);
    }
}

src/app/Http/Controllers/BoxTemplateController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\BoxTemplate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class BoxTemplateController extends Controller
{
    public function index(Request $request)
    {
        $boxTemplates = BoxTemplate::all();
        return view('boxTemplates.index', compact('boxTemplates'));
    }

    public function create(Request $request)
    {
        $products = Product::all()->pluck('title', 'id');
        return view('boxTemplates.create',compact('products'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title'         => 'required',
            'products'         => 'required|array',
            'targets' => 'required|array',
        ]);

        $input = $request->except(['products','targets']);

        $record = BoxTemplate::create($input);

        $products = $request->input('products',[]);
        $targets = $request->input('targets',[]);
        $productIdsAndPivotValues = [];
        foreach($products as $index => $productId){
            $productIdsAndPivotValues[$productId] = ['target' => $targets[$productId]];
        }
        $record->products()->sync($productIdsAndPivotValues);

        return redirect()->route('boxTemplates.index');
    }

    public function show(BoxTemplate $boxTemplate)
    {
        return view('boxTemplates.show',compact('boxTemplate'));
    }

    public function edit(BoxTemplate $boxTemplate)
    {
        $products = Product::all()->pluck('title', 'id');
        $productsNumberToId = json_encode(Product::all()->pluck('id', 'number'));
        return view('boxTemplates.edit',compact('boxTemplate','products','productsNumberToId'));
    }

    public function update(Request $request, BoxTemplate $boxTemplate)
    {
        $this->validate($request, [
            'title' => 'required',
            'products' => 'nullable|array',
            'targets' => 'nullable|array',
        ]);

        $input = $request->except(['products','targets']);
        $boxTemplate->update($input);

        //sync the products
        $products = $request->input('products',[]);
        $targets = $request->input('targets',[]);
        $productIdsAndPivotValues = [];
        foreach($products as $productId){
            $productIdsAndPivotValues[$productId] = ['target' => $targets[$productId]];
        }
        $boxTemplate->products()->sync($productIdsAndPivotValues);

        $boxes = $boxTemplate->boxes;
        foreach($boxes as $box){
            $box->products()->syncWithoutDetaching($productIdsAndPivotValues);
        }

        return redirect()->route('boxTemplates.index');
    }

    public function destroy(BoxTemplate $boxTemplate)
    {
        if($boxTemplate->boxes()->count() !== 0){
            return Redirect::back()->withErrors(["relations" => 'Es existieren noch Fremdbeziehungen.']);
        }
        $boxTemplate->products()->detach();
        $boxTemplate->delete();
        return redirect()->route('boxTemplates.index');
    }
}

src/resources/views/boxTemplates/create.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('boxTemplates.create') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("boxTemplates.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('boxTemplates.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}" required>
                @if($errors->has('title'))
                    <div class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('boxTemplates.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="products">{{ trans('boxTemplates.products') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('general.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('products') ? 'is-invalid' : '' }}" name="products[]" id="products" multiple required>
                    @foreach($products as $id => $product)
                        <option value="{{ $id }}" {{ in_array($id, old('products', [])) ? 'selected' : '' }}>{{ $product }}</option>
                    @endforeach
                </select>
                @if($errors->has('products'))
                    <div class="invalid-feedback">
                        {{ $errors->first('products') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('boxTemplates.products_helper') }}</span>
            </div>
            <div class="table-responsive">
                <table id="productsTable" class="table table-sm table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="w-7">{{ __('boxTemplates.product') }}</th>
                            <th>{{ __('boxTemplates.target') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('general.save') }}
                </button>
                <a class="btn btn-secondary" href="{{ route('boxTemplates.index') }}">
                    {{ trans('general.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')

<script>

    var cell2HTML ='<input class="form-control" name="targets[]" type="number" value="0" min="0">'
    var table = document.getElementById('productsTable')

        $('.select2').on('select2:select', function (e) {
            var selectedProductName = e.params.data.element.innerHTML;
            var selectedProductId = e.params.data.element.value;
            var newRowId = 'product_row_'+selectedProductId
            var exisitingRow = document.getElementById(newRowId)
            if(!exisitingRow){
                var newRow = table.insertRow()
                newRow.id = newRowId
                var cell1 = newRow.insertCell()
                cell1.innerHTML = selectedProductName
                var cell2 = newRow.insertCell()
                cell2.innerHTML = cell2HTML
                cell2.children[0].name = `targets[${selectedProductId}]`
            }
        });
        $('.select2').on('select2:unselect', function (e) {
            var selectedProductId = e.params.data.element.value;
            var selectedProductRowId = "product_row_"+selectedProductId
            var selectedProductRow = document.getElementById(selectedProductRowId)
            if(selectedProductRow){
                selectedProductRow.parentNode.removeChild(selectedProductRow)
            }
        });
        $('.deselect-all').click(function () {
           while(table.rows.length > 1){
               table.deleteRow(-1)
           }
        })

</script>

@endsection

src/resources/views/boxTemplates/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('boxTemplates.edit') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("boxTemplates.update", [$boxTemplate->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('boxTemplates.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $boxTemplate->title) }}" required>
                @if($errors->has('title'))
                    <div class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('boxTemplates.title_helper') }}</span>
            </div>
            @include('components.productSelect',["model" => $boxTemplate])
            <div class="table-responsive">
                <table id="productsTable" class="table table-sm table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="w-7">{{ __('boxTemplates.product') }}</th>
                            <th>{{ __('boxTemplates.target') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($boxTemplate->products as $product)
                            <tr id="product_row_{{$product->id}}">
                                <td>
                                    {{ $product->title }}
                                </td>
                                <td><div class="input-group"><input class="form-control" name="targets[{{$product->id}}]" id="target_{{$product->id}}" type="number" value="{{ $product->pivot->target ?? 0}}" step="1" min="0"><div class="input-group-append"><button class="btn btn-outline-primary" type="button" style="touch-action: manipulation;" onclick="document.getElementById(&quot;target_{{$product->id}}&quot;).stepUp();document.getElementById(&quot;target_{{$product->id}}&quot;).dispatchEvent(new Event('change'))">+</button><button class="btn btn-outline-primary" type="button" style="touch-action: manipulation;" onclick="document.getElementById(&quot;target_{{$product->id}}&quot;).stepDown();document.getElementById(&quot;target_{{$product->id}}&quot;).dispatchEvent(new Event('change'))">-</button></div></div></div></div></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('general.save') }}
                </button>
                <a class="btn btn-secondary" href="{{ route('boxTemplates.index') }}">
                    {{ trans('general.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>

@endSection

@section('scripts')

<script>
    window.useQrScanner = "true"

    var cell2HTML ='<div class="input-group"><input class="form-control" name="targets[]" type="number" value="1" step="1" min="0"><div class="input-group-append"><button class="btn btn-outline-primary" type="button">+</button><button class="btn btn-outline-primary" type="button">-</button></div></div></div></div>'

    var table = document.getElementById('productsTable')

    $('.select2').on('select2:select', function (e) {
        var selectedProductName = e.params.data.element.innerHTML;
        var selectedProductId = e.params.data.element.value;
        var newRowId = 'product_row_'+selectedProductId
        var exisitingRow = document.getElementById(newRowId)
        if(!exisitingRow){
            var newRow = table.insertRow()
            newRow.id = newRowId
            var cell1 = newRow.insertCell()
            cell1.innerHTML = selectedProductName

            var cell2 = newRow.insertCell()
            cell2.innerHTML = cell2HTML
            var input3 =  cell2.getElementsByTagName('input')[0]
            input3.name = `targets[${selectedProductId}]`
            input3.id = 'target_'+selectedProductId
            var button1 =  cell2.getElementsByTagName('button')[0]
            button1.addEventListener('click', () => {input3.stepUp();  input3.dispatchEvent(new Event('change'))});
            button1.style.cssText += "touch-action: manipulation;"//prevent double tap
            var button2 =  cell2.getElementsByTagName('button')[1]
            button2.addEventListener('click', () => {input3.stepDown(); input3.dispatchEvent(new Event('change'))});
            button2.style.cssText += "touch-action: manipulation;"//prevent double tap
        }
    });
    $('.select2').on('select2:unselect', function (e) {
        var selectedProductId = e.params.data.element.value;
        var selectedProductRowId = "product_row_"+selectedProductId
        var selectedProductRow = document.getElementById(selectedProductRowId)
        if(selectedProductRow){
            selectedProductRow.parentNode.removeChild(selectedProductRow)
        }
    });
    $('.deselect-all').click(function () {
        while(table.rows.length > 1){
            table.deleteRow(-1)
        }
    })

</script>

@endsection

src/resources/views/boxTemplates/index.blade.php
@extends('layouts.app')
@section('content')

<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success {{auth()->user()->can("create boxTemplates") ? '' : 'disabled'}}" href="{{ route("boxTemplates.create") }}">
            {{ trans('boxTemplates.add') }}
        </a>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('boxTemplates.list') }}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('boxTemplates.title') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($boxTemplates as $key => $boxTemplate)
                        <tr data-entry-id="{{ $boxTemplate->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $boxTemplate->title ?? '' }}
                            </td>
                            <td>
                                    <a class="btn btn-xs btn-primary {{auth()->user()->can("view boxTemplates") ? '' : 'disabled'}}" href="{{ route('boxTemplates.show', $boxTemplate->id) }}">
                                        {{ trans('general.view') }}
                                    </a>

                                    <a class="btn btn-xs btn-info {{auth()->user()->can("edit boxTemplates") ? '' : 'disabled'}}" href="{{ route('boxTemplates.edit', $boxTemplate->id) }}">
                                        {{ trans('general.edit') }}
                                    </a>

                                    <form action="{{ route('boxTemplates.destroy', $boxTemplate->id) }}" method="POST" onsubmit="return confirm('{{ trans('general.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger {{auth()->user()->can("delete boxTemplates") ? '' : 'disabled'}}" value="{{ trans('general.delete') }}">
                                    </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endSection

src/resources/views/boxTemplates/show.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('boxTemplates.model') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('boxTemplates.index') }}">
                    {{ trans('general.back_to_list') }}
                </a>
            </div>
            <p><strong>{{ $boxTemplate->title }}</strong></p>
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            {{ trans('boxTemplates.product') }}
                        </th>
                        <th>
                            {{ trans('boxTemplates.target') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($boxTemplate->products as $key => $product)
                    <tr>
                        <td>
                            {{ $product->title }}
                        </td>
                        <td>
                            {{$product->pivot->target}}
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('boxTemplates.index') }}">
                    {{ trans('general.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

@endSection