src/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoxController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\BoxTemplateController;
use App\Http\Controllers\TransactionController;

require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', function () {
        return redirect("/boxes/".Auth::user()->box->id);
    });

    Route::resource('permissions', PermissionController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('transactions', TransactionController::class);
    Route::resource('boxTemplates', BoxTemplateController::class);
    Route::resource('boxes', BoxController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('orders', OrderController::class);
});

src/app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    public $table = "customers";

    protected $guarded = [];

    public function orders () {
        return $this->hasMany(Order::class);
    }

    public function getNameAttribute()
    {
        return $this->company ?? $this->last_name;
    }
}

src/app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $customers = Customer::all();
        return view('customers.index', compact('customers'));
    }

    public function create(Request $request)
    {
        return view('customers.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'company'         => 'required_without:last_name',
            'last_name'         => 'required_without:company',
        ]);

        $input = $request->all();

        $record = Customer::create($input);

        return redirect()->route('customers.index');
    }

    public function show(Customer $customer)
    {
        return view('customers.show',compact('customer'));
    }

    public function edit(Customer $customer)
    {
        return view('customers.edit',compact('customer'));
    }

    public function update(Request $request, Customer $customer)
    {
        $this->validate($request, [
            'company' => 'required',
        ]);

        $input = $request->all();
        $customer->update($input);

        return redirect()->route('customers.index');
    }

    public function destroy(Customer $customer)
    {
        if($customer->orders()->count() !== 0){
            return Redirect::back()->withErrors(["relations" => 'Es existieren noch Fremdbeziehungen.']);
        }
        $customer->delete();
        return redirect()->route('customers.index');
    }
}

src/resources/views/customers/create.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('customers.create') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("customers.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="company">{{ trans('customers.company') }}</label>
                <input class="form-control {{ $errors->has('company') ? 'is-invalid' : '' }}" type="text" name="company" value="{{ old('company', '') }}" required>
                @if($errors->has('company'))
                    <div class="invalid-feedback">
                        {{ $errors->first('company') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="first_name">{{ trans('customers.first_name') }}</label>
                <input class="form-control {{ $errors->has('first_name') ? 'is-invalid' : '' }}" type="text" name="first_name" value="{{ old('first_name', '') }}" >
                @if($errors->has('first_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('first_name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label class="required" for="last_name">{{ trans('customers.last_name') }}</label>
                <input class="form-control {{ $errors->has('last_name') ? 'is-invalid' : '' }}" type="text" name="last_name" value="{{ old('last_name', '') }}" >
                @if($errors->has('last_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('last_name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="street">{{ trans('customers.street') }}</label>
                <input class="form-control {{ $errors->has('street') ? 'is-invalid' : '' }}" type="text" name="street" value="{{ old('street', '') }}" >
                @if($errors->has('street'))
                    <div class="invalid-feedback">
                        {{ $errors->first('street') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="zip">{{ trans('customers.zip') }}</label>
                <input class="form-control {{ $errors->has('zip') ? 'is-invalid' : '' }}" type="text" name="zip" value="{{ old('zip', '') }}" >
                @if($errors->has('zip'))
                    <div class="invalid-feedback">
                        {{ $errors->first('zip') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="city">{{ trans('customers.city') }}</label>
                <input class="form-control {{ $errors->has('city') ? 'is-invalid' : '' }}" type="text" name="city" value="{{ old('city', '') }}" >
                @if($errors->has('city'))
                    <div class="invalid-feedback">
                        {{ $errors->first('city') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="email">{{ trans('customers.email') }}</label>
                <input class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="text" name="email" value="{{ old('email', '') }}" >
                @if($errors->has('email'))
                    <div class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="phone">{{ trans('customers.phone') }}</label>
                <input class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" type="text" name="phone" value="{{ old('phone', '') }}" >
                @if($errors->has('phone'))
                    <div class="invalid-feedback">
                        {{ $errors->first('phone') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="website">{{ trans('customers.website') }}</label>
                <input class="form-control {{ $errors->has('website') ? 'is-invalid' : '' }}" type="text" name="website" value="{{ old('website', '') }}" >
                @if($errors->has('website'))
                    <div class="invalid-feedback">
                        {{ $errors->first('website') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('general.save') }}
                </button>
                <a class="btn btn-secondary" href="{{ route('customers.index') }}">
                    {{ trans('general.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>



@endsection

src/resources/views/customers/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('customers.edit') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("customers.update", [$customer->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="company">{{ trans('customers.company') }}</label>
                <input class="form-control {{ $errors->has('company') ? 'is-invalid' : '' }}" type="text" name="company" value="{{ old('company', $customer->company) }}" required>
                @if($errors->has('company'))
                    <div class="invalid-feedback">
                        {{ $errors->first('company') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="first_name">{{ trans('customers.first_name') }}</label>
                <input class="form-control {{ $errors->has('first_name') ? 'is-invalid' : '' }}" type="text" name="first_name" value="{{ old('first_name', $customer->first_name) }}" >
                @if($errors->has('first_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('first_name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label class="required" for="last_name">{{ trans('customers.last_name') }}</label>
                <input class="form-control {{ $errors->has('last_name') ? 'is-invalid' : '' }}" type="text" name="last_name" value="{{ old('last_name', $customer->last_name) }}" >
                @if($errors->has('last_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('last_name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="street">{{ trans('customers.street') }}</label>
                <input class="form-control {{ $errors->has('street') ? 'is-invalid' : '' }}" type="text" name="street" value="{{ old('street', $customer->street) }}" >
                @if($errors->has('street'))
                    <div class="invalid-feedback">
                        {{ $errors->first('street') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="zip">{{ trans('customers.zip') }}</label>
                <input class="form-control {{ $errors->has('zip') ? 'is-invalid' : '' }}" type="text" name="zip" value="{{ old('zip', $customer->zip) }}" >
                @if($errors->has('zip'))
                    <div class="invalid-feedback">
                        {{ $errors->first('zip') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="city">{{ trans('customers.city') }}</label>
                <input class="form-control {{ $errors->has('city') ? 'is-invalid' : '' }}" type="text" name="city" value="{{ old('city', $customer->city) }}" >
                @if($errors->has('city'))
                    <div class="invalid-feedback">
                        {{ $errors->first('city') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="email">{{ trans('customers.email') }}</label>
                <input class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="text" name="email" value="{{ old('email', $customer->email) }}" >
                @if($errors->has('email'))
                    <div class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="phone">{{ trans('customers.phone') }}</label>
                <input class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" type="text" name="phone" value="{{ old('phone', $customer->phone) }}" >
                @if($errors->has('phone'))
                    <div class="invalid-feedback">
                        {{ $errors->first('phone') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label  for="website">{{ trans('customers.website') }}</label>
                <input class="form-control {{ $errors->has('website') ? 'is-invalid' : '' }}" type="text" name="website" value="{{ old('website', $customer->website) }}" >
                @if($errors->has('website'))
                    <div class="invalid-feedback">
                        {{ $errors->first('website') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('general.save') }}
                </button>
                <a class="btn btn-secondary" href="{{ route('customers.index') }}">
                    {{ trans('general.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>

@endSection

src/resources/views/customers/index.blade.php
@extends('layouts.app')
@section('content')

<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success {{auth()->user()->can("create customers") ? '' : 'disabled'}}" href="{{ route("customers.create") }}">
            {{ trans('customers.add') }}
        </a>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('customers.list') }}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('customers.company') }}
                        </th>
                        <th>
                            {{ trans('customers.first_name') }}
                        </th>
                        <th>
                            {{ trans('customers.last_name') }}
                        </th>
                        <th>
                            {{ trans('customers.email') }}
                        </th>
                        <th>
                            {{ trans('customers.phone') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($customers as $key => $customer)
                        <tr data-entry-id="{{ $customer->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $customer->company ?? '' }}
                            </td>
                            <td>
                                {{ $customer->first_name ?? '' }}
                            </td>
                            <td>
                                {{ $customer->last_name ?? '' }}
                            </td>
                            <td>
                                @if($customer->email)
                                <a href = "mailto: {{ $customer->email }}">{{ $customer->email }}</a>
                                @endif
                            </td>
                            <td>
                                {{ $customer->phone ?? '' }}
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary {{auth()->user()->can("view customers") ? '' : 'disabled'}}" href="{{ route('customers.show', $customer->id) }}">
                                    {{ trans('general.view') }}
                                </a>

                                <a class="btn btn-xs btn-info {{auth()->user()->can("edit customers") ? '' : 'disabled'}}" href="{{ route('customers.edit', $customer->id) }}">
                                    {{ trans('general.edit') }}
                                </a>

                                <form action="{{ route('customers.destroy', $customer->id) }}" method="POST" onsubmit="return confirm('{{ trans('general.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger {{auth()->user()->can("delete customers") ? '' : 'disabled'}}" value="{{ trans('general.delete') }}">
                                </form>

                                <a class="btn btn-xs btn-success" {{auth()->user()->can("create orders") ? '' : 'disabled'}} href="{{"/orders/create?cid=".$customer->id}}">
                                    {{ trans('orders.create') }}
                                </a>
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endSection

src/resources/views/customers/show.blade.php
@extends('layouts.app')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('customers.model') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('customers.index') }}">
                    {{ trans('general.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('customers.company') }}
                        </th>
                        <td>
                            {{ $customer->company }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.first_name') }}
                        </th>
                        <td>
                            {{ $customer->first_name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.last_name') }}
                        </th>
                        <td>
                            {{ $customer->last_name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.street') }}
                        </th>
                        <td>
                            {{ $customer->street }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.zip') }}
                        </th>
                        <td>
                            {{ $customer->zip }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.city') }}
                        </th>
                        <td>
                            {{ $customer->city }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.email') }}
                        </th>
                        <td>
                            {{ $customer->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.phone') }}
                        </th>
                        <td>
                            {{ $customer->phone }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('customers.website') }}
                        </th>
                        <td>
                            {{ $customer->website }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('customers.index') }}">
                    {{ trans('general.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

@endSection